<?php

declare(strict_types=1);

namespace ksfraser\FrontAccounting\HRM\Controller;

use ksfraser\FrontAccounting\Common\App\AbstractTabController;
use ksfraser\FrontAccounting\HRM\Service\DepartmentService;
use ksfraser\FrontAccounting\HRM\Service\PositionService;
use ksfraser\FrontAccounting\HRM\Service\RoleService;
use ksfraser\FrontAccounting\HRM\Service\TeamService;

/**
 * PositionsTabController — controller SRP for the HRM Positions tab.
 *
 * Summary table above (paged, Edit/Deactivate), entry form below. The
 * position_code is generated by PositionRepository::generatePositionCode()
 * from the department/team selection, so it is a table column only and is
 * not editable in the form.
 *
 * Row delete is a soft delete via PositionService::deactivate(), which
 * deliberately clears is_active only — PositionRepository::update() writes
 * team_id unconditionally and would wipe the assignment.
 *
 * PHP 7.3 compatible.
 *
 * @package ksf_FA_HRM
 * @since   1.0.0
 *
 * @UML Note: APP_TAB_ARCHITECTURE.md §2/§10
 * @BABOK Related: FR-HRM-001
 */
class PositionsTabController extends AbstractTabController
{
    /** @var PositionService */
    private $service;

    /** @var DepartmentService */
    private $departmentService;

    /** @var TeamService */
    private $teamService;

    /** @var RoleService */
    private $roleService;

    /**
     * @param \Ksfraser\Frontaccounting\HTML\TabContext|null $context DI request state
     * @param array<string, mixed>                            $options
     *
     * @since 1.0.0
     */
    public function __construct($context = null, array $options = [])
    {
        parent::__construct($context, $options);
        $this->service = new PositionService();
        $this->departmentService = new DepartmentService();
        $this->teamService = new TeamService();
        $this->roleService = new RoleService();
    }

    /** {@inheritDoc} */
    protected function getPkField(): string
    {
        return 'position_id';
    }

    /** {@inheritDoc} */
    protected function getFieldMetadata(): array
    {
        return [
            'entity'      => 'position',
            'table'       => TB_PREF . 'hrm_positions',
            'label'       => 'Position',
            'labelPlural' => 'Positions',
            'hookPrefix'  => 'position',
            'pk'          => 'position_id',
            'fields'      => [
                'position_id' => [
                    'label' => 'ID',
                    'type'  => 'text',
                    'showInForm' => false,
                    'showInTable' => false,
                ],
                'position_code' => [
                    'label' => 'Code',
                    'type'  => 'text',
                    'showInForm' => false,
                    'showInTable' => true,
                ],
                'department_id' => [
                    'label' => 'Department',
                    'type'  => 'select',
                    'showInForm' => true,
                    'showInTable' => false,
                    'colClass' => 'col-md-4',
                ],
                'team_id' => [
                    'label' => 'Team',
                    'type'  => 'select',
                    'showInForm' => true,
                    'showInTable' => false,
                    'colClass' => 'col-md-4',
                ],
                'role_id' => [
                    'label' => 'Role',
                    'type'  => 'select',
                    'showInForm' => true,
                    'showInTable' => false,
                    'colClass' => 'col-md-4',
                ],
                'department_code' => [
                    'label' => 'Department',
                    'type'  => 'text',
                    'showInForm' => false,
                    'showInTable' => true,
                ],
                'team_code' => [
                    'label' => 'Team',
                    'type'  => 'text',
                    'showInForm' => false,
                    'showInTable' => true,
                ],
                'role_name' => [
                    'label' => 'Role',
                    'type'  => 'text',
                    'showInForm' => false,
                    'showInTable' => true,
                ],
                'description' => [
                    'label' => 'Description',
                    'type'  => 'textarea',
                    'rows' => 2,
                    'showInForm' => true,
                    'showInTable' => false,
                    'colClass' => 'col-md-8',
                ],
                'is_active' => [
                    'label' => 'Active',
                    'type'  => 'checkbox',
                    'default' => 1,
                    'showInTable' => true,
                    'showInForm' => true,
                    'colClass' => 'col-md-2',
                ],
            ],
            'fk_ddls'   => [],
            'ddlHooks'  => [],
            'tableSettings' => ['orderBy' => 'position_code ASC'],
        ];
    }

    /**
     * The three FK selects. Service getHtmlOptions() returns HtmlOption[]
     * objects; FieldForm wants a plain value => label map.
     *
     * @return array<string, array<string, string>>
     */
    protected function fkOptions(): array
    {
        return [
            'department_id' => $this->toOptionMap($this->departmentService->getHtmlOptions(true, $this->localise('All'))),
            'team_id'       => $this->toOptionMap($this->teamService->getHtmlOptions(true, $this->localise('None'))),
            'role_id'       => $this->toOptionMap($this->roleService->getHtmlOptions(true, $this->localise('None'))),
        ];
    }

    /**
     * @param array $options HtmlOption[] from a service getHtmlOptions() call
     * @return array<string, string> value => label
     */
    private function toOptionMap(array $options): array
    {
        $map = [];
        foreach ($options as $option) {
            if (is_object($option) && method_exists($option, 'getValue')) {
                $map[(string) $option->getValue()] = (string) $option->getLabel();
            } elseif (is_array($option)) {
                $map[(string) ($option['value'] ?? '')] = (string) ($option['label'] ?? '');
            }
        }
        return $map;
    }

    /** {@inheritDoc} */
    protected function listRows(int $page, int $perPage): array
    {
        $rows = [];
        $offset = ($page - 1) * $perPage;
        $all = $this->service->listAllIncludingInactive();
        foreach (array_slice($all, $offset, $perPage) as $position) {
            $rows[] = $position->toArray();
        }
        return $rows;
    }

    /** {@inheritDoc} */
    protected function countRows(): int
    {
        return count($this->service->listAllIncludingInactive());
    }

    /** {@inheritDoc} */
    protected function findRecord(string $pk): ?array
    {
        $position = $this->service->getById((int) $pk);
        return empty($position) ? null : $position;
    }

    /** {@inheritDoc} */
    protected function createRecord(array $data)
    {
        return $this->service->create($data);
    }

    /** {@inheritDoc} */
    protected function updateRecord(string $pk, array $data): void
    {
        $this->service->update((int) $pk, $data);
    }

    /** {@inheritDoc} */
    protected function deleteRecord(string $pk): void
    {
        $this->service->deactivate((int) $pk);
    }

    /** {@inheritDoc} */
    protected function getActionLabels(): array
    {
        return [
            'edit'   => $this->localise('Edit'),
            'delete' => $this->localise('Deactivate'),
        ];
    }

    /** {@inheritDoc} */
    protected function getDeleteConfirmMessage(): string
    {
        return $this->localise('Deactivate this position? Employees holding it keep their assignment.');
    }
}
